SET PAGESIZE 40 
SET LINESIZE 180 
SET SERVEROUTPUT ON 
SET ECHO ON

SPOOL Project3.log;

DROP TABLE Customer_T CASCADE CONSTRAINTS;

DROP TABLE Director_T CASCADE CONSTRAINTS;

DROP TABLE Actor_T CASCADE CONSTRAINTS;

DROP TABLE Distributor_T CASCADE CONSTRAINTS;

DROP TABLE Movie CASCADE CONSTRAINTS;

DROP TABLE AcademyAward_T CASCADE CONSTRAINTS;

DROP TABLE Rental_T CASCADE CONSTRAINTS;

DROP TABLE Inventory CASCADE CONSTRAINTS;

CREATE TABLE Customer_T(
CustomerID NUMBER(6) NOT NULL,
FirstName VARCHAR2(20),
LastName VARCHAR2(20),
Address VARCHAR2(30),
City VARCHAR2(20),
State CHAR (2),
Zip NUMBER(10),
PhoneNumber NUMBER(10),
CONSTRAINT CustID_PK PRIMARY KEY (CustomerID)
);

CREATE TABLE Director_T(
DirectorID NUMBER(8),
FirstName VARCHAR2(25),
LastName VARCHAR2(25),
CONSTRAINT DirectorID_PK PRIMARY KEY (DirectorID)
);

CREATE TABLE Actor_T(
ActorID NUMBER(10) NOT NULL,
FirstName VARCHAR2(25),
LastName VARCHAR2(25),
CONSTRAINT ActorID_PK PRIMARY KEY (ActorID)
);

CREATE TABLE Distributor_T(
DistributorID NUMBER(8) NOT NULL,
DistributorName VARCHAR2(25),
Address VARCHAR2(60),
PhoneNumber NUMBER(10),
Email VARCHAR2(40),
CONSTRAINT DistributorID_PK PRIMARY KEY (DistributorID)
);

CREATE TABLE Movie (
MovieID NUMBER(8),
Title VARCHAR2(25),
Year NUMBER(8),
Dvd VARCHAR2(8),
Vhs VARCHAR2(8),
Genre VARCHAR2(25),
CONSTRAINT MovieID_PK PRIMARY KEY (MovieID)
);

CREATE TABLE AcademyAward_T(
AcademyAwardID NUMBER(15),
Title VARCHAR2(25),
YearWon NUMBER(15),
CONSTRAINT AcademyAward_PK PRIMARY KEY (AcademyAwardID)
);

CREATE TABLE Rental_T(
RentalID NUMBER(8) NOT NULL,
CustomerID NUMBER(8) NOT NULL,
MovieID NUMBER(8) NOT NULL,
DateRented DATE DEFAULT SYSDATE,
DateReturned DATE DEFAULT SYSDATE,
Price Decimal (6,2),
Fee Decimal (6,2),
CONSTRAINT RentalID_PK PRIMARY KEY (RentalID),
CONSTRAINT Rental_FK1 FOREIGN KEY (CustomerID) REFERENCES Customer_T (CustomerID),
CONSTRAINT Rental_FK2 FOREIGN KEY (MovieID) REFERENCES Movie (MovieID)
);

CREATE TABLE Inventory (
InventoryID NUMBER(8) NOT NULL,
MovieID NUMBER(8) NOT NULL,
DistributorID NUMBER(8),
CONSTRAINT InventoryID_PK PRIMARY KEY (InventoryID),
CONSTRAINT Inventory_FK1 FOREIGN KEY (MovieID) REFERENCES Movie (MovieID),
CONSTRAINT Inventory_FK2 FOREIGN KEY (DistributorID) REFERENCES Distributor_T (DistributorID)
);

SET SERVEROUTPUT OFF

SPOOL OFF;






